# Generated by Django 5.0.6 on 2024-05-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('origem', models.CharField(default='usuario', max_length=10)),
                ('cnpj', models.CharField(max_length=20)),
                ('razao_social', models.CharField(max_length=100)),
                ('porte', models.CharField(max_length=3)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('uf', models.CharField(max_length=2)),
                ('municipio', models.CharField(max_length=50)),
                ('logradouro', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=5)),
                ('cep', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
