# Generated by Django 5.0.6 on 2024-05-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='criador_por',
            new_name='criado_por',
        ),
    ]
