# Generated by Django 5.0.6 on 2024-05-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('A', 'Atendente'), ('G', 'Gerente')], default='Gerente', max_length=10),
            preserve_default=False,
        ),
    ]
